"""Logic for the `init` command: build a scenario-correct ``.env``.

This module is deliberately free of I/O and prompts so it can be unit-tested. The
interactive wiring (questions, password entry, pip install) lives in ``main.py``;
here we only turn a set of answers into ``.env`` text and answer a couple of
filesystem questions.

The design is a *smart ``cp .env.example .env``*: every non-secret variable is
written correct for the chosen scenario, and only the one relevant provider key is
emitted as a labelled blank for the user to fill.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

# Curated model map: one recommended model string per provider, plus the env var that
# holds that provider's key. Strings mirror the ones documented in .env.example and
# config.py so we ship nothing we haven't already vetted in the repo. Update here (not
# in prompts) when a provider's recommended model changes.
PROVIDERS: dict[str, dict[str, str]] = {
    "openai": {"label": "OpenAI", "model": "openai:gpt-4o", "key_var": "OPENAI_API_KEY"},
    "anthropic": {
        "label": "Anthropic",
        "model": "anthropic:claude-sonnet-4-5",
        "key_var": "ANTHROPIC_API_KEY",
    },
    "groq": {
        "label": "Groq",
        "model": "groq:llama-3.3-70b-versatile",
        "key_var": "GROQ_API_KEY",
    },
    "deepseek": {
        "label": "DeepSeek",
        "model": "deepseek:deepseek-chat",
        "key_var": "DEEPSEEK_API_KEY",
    },
    "google": {
        "label": "Google",
        "model": "google:gemini-2.0-flash",
        "key_var": "GEMINI_API_KEY",
    },
}

# Local SQLite URL matching the shipped .env.example default. Writing it explicitly
# (rather than leaving DATABASE_URL unset) makes a "local" install durable for BOTH
# auth and conversation memory, since memory's "auto" backend follows DATABASE_URL.
LOCAL_SQLITE_URL = "sqlite+aiosqlite:///./pydankit.db"
POSTGRES_PLACEHOLDER = "postgresql+asyncpg://USER:PASSWORD@HOST:5432/DBNAME"


@dataclass
class InstallerAnswers:
    """The user's scenario choices, resolved from the interactive prompts."""

    run_mode: str  # "cli" | "web"
    provider: str  # a key of PROVIDERS
    persistence: str  # "local" | "postgres"
    auth: str  # "open" | "multi"
    agent_name: str = "PydanKit"
    admin_username: str | None = None
    admin_password: str | None = None

    @property
    def web(self) -> bool:
        return self.run_mode == "web"

    @property
    def multi_user(self) -> bool:
        return self.auth == "multi"

    @property
    def needs_admin_seed(self) -> bool:
        """Admin seeding only makes sense for a multi-user web dashboard."""
        return self.web and self.multi_user


def build_env_content(answers: InstallerAnswers) -> str:
    """Render the ``.env`` text for the given answers.

    Pure and deterministic — no filesystem, no secrets read from anywhere except the
    ``admin_password`` the caller already collected. Only the chosen provider's key
    slot is emitted, so there is no wrong slot to paste a key into.
    """
    prov = PROVIDERS[answers.provider]
    lines: list[str] = [
        "# Generated by `python -m src.main init`.",
        "# Non-secret settings below are pre-filled for your chosen setup. Paste your",
        "# API key where marked and you're ready to run.",
        "",
        "# --- Identity ---",
        "# Branding shown on the dashboard, the browser tab, and the API/Swagger title.",
        f"AGENT_NAME={answers.agent_name}",
        "",
        "# --- Model ---",
        "# Recommended model for your provider. Pick another your account can access if",
        "# you like (see the comments in .env.example for the format).",
        f"MODEL_NAME={prov['model']}",
        "",
        f"# >>> PASTE YOUR {prov['label'].upper()} API KEY BELOW <<<",
        f"{prov['key_var']}=",
        "",
    ]

    if answers.web:
        lines += [
            "# --- API server (used by the `serve` command) ---",
            "# The origin(s) the dashboard/API is served from. Credentials are always on,",
            "# so this can never be [\"*\"]. CHANGE THIS to your real URL before deploying.",
            'CORS_ORIGINS=["http://localhost:8000"]',
            "",
        ]

    lines += ["# --- Authentication ---"]
    if answers.multi_user:
        lines += ["AUTH_ENABLED=true"]
    else:
        lines += [
            "# Open mode: the API requires no login (the CLI is always a trusted shell).",
            "AUTH_ENABLED=false",
        ]

    if answers.persistence == "postgres":
        lines += [
            "# Postgres backend for users, tokens, and durable memory. Fill in real",
            "# credentials. Requires the [postgres] extra: pip install -e .[postgres]",
            f"DATABASE_URL={POSTGRES_PLACEHOLDER}",
        ]
    else:
        lines += [
            "# Local SQLite backend (durable for auth and conversation memory).",
            f"DATABASE_URL={LOCAL_SQLITE_URL}",
        ]

    if answers.needs_admin_seed:
        lines += [
            "",
            "# First admin, seeded on first `serve` when no admin exists yet.",
            "# SECURITY: the password is stored in plaintext here. Rotate or clear it",
            "# after your first login.",
            f"ADMIN_USERNAME={answers.admin_username}",
            f"ADMIN_PASSWORD={answers.admin_password}",
        ]

    if answers.web:
        lines += [
            "",
            "# Set true in any deployment served over HTTPS (marks the session cookie",
            "# Secure). Leave false only for local http.",
            "SESSION_COOKIE_SECURE=false",
        ]

    return "\n".join(lines) + "\n"


def required_extras(answers: InstallerAnswers) -> list[tuple[str, str]]:
    """Return the ``(extra_name, probe_import)`` pairs the chosen scenario needs.

    The base install ships neither the API server nor a database driver, so a scenario
    that writes a ``DATABASE_URL`` or runs the dashboard needs an extra installed — else
    "paste your key and it works" breaks at first run. ``probe_import`` is a module the
    caller can look up to decide whether the extra is already present.

    - Web dashboard → ``[api]`` (FastAPI, and it bundles the auth/db drivers too).
    - Postgres persistence → ``[postgres]`` (asyncpg).
    - Local SQLite persistence → a driver (aiosqlite, in ``[auth]``). ``[api]`` already
      bundles it, so only CLI + local needs ``[auth]`` on its own.
    """
    extras: list[tuple[str, str]] = []
    if answers.web:
        extras.append(("api", "fastapi"))
    if answers.persistence == "postgres":
        extras.append(("postgres", "asyncpg"))
    elif answers.persistence == "local" and not answers.web:
        extras.append(("auth", "aiosqlite"))
    return extras


def extra_install_command(
    extra: str, *, python_executable: str, has_pip: bool, has_uv: bool
) -> tuple[list[str] | None, str]:
    """Choose how to install an optional extra, adapting to the environment.

    Returns ``(argv, hint)`` where ``argv`` is the command to run (or ``None`` if we
    can't install automatically) and ``hint`` is the equivalent command as a string for
    the user to run themselves.

    Prefers ``python -m pip`` (present in a standard venv). Falls back to ``uv pip
    install`` when the interpreter has no pip — uv-created venvs ship without it — and
    pins ``--python`` so it targets the same interpreter running ``init`` regardless of
    activation. If neither pip nor uv is available, ``argv`` is ``None``.
    """
    target = f".[{extra}]"
    if has_pip:
        argv = [python_executable, "-m", "pip", "install", "-e", target]
        return argv, f"pip install -e '{target}'"
    if has_uv:
        return (
            ["uv", "pip", "install", "--python", python_executable, "-e", target],
            f"uv pip install -e '{target}'",
        )
    return None, f"pip install -e '{target}'"


def env_is_gitignored(project_root: Path) -> bool:
    """Whether ``.gitignore`` ignores ``.env`` (best-effort, plain-line match).

    Guards against writing an admin password into a file that could be committed. If
    there is no ``.gitignore`` at all we return False so the caller warns rather than
    assuming safety.
    """
    gitignore = project_root / ".gitignore"
    if not gitignore.exists():
        return False
    for raw in gitignore.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line in (".env", "*.env", "/.env"):
            return True
    return False
